// Printable policy documents generated by servicing events.
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { Download, Printer, X } from 'lucide-react';
import { downloadDeclarationsPdf, downloadPolicyPacket, type PacketCopy } from '@/services/pdf/policyPdf';
import type { PolicyDocument, PolicyRecord } from '@/types/policy';
import { formatCurrency } from '@/utils/masks';
import { DOCUMENT_TITLES } from '@/servicing/documentTitles';
import { CLAIMS_LINE } from '@/servicing/portal/portalUtils';
import { rulesFor } from '@/data/states';
import { notify } from '@/services/activity';
import { LOGO_URL } from '@/services/pdf/logo';
import { LATE_FEE } from '@/services/policyEngine';

const money = (value: unknown) => formatCurrency(Number(value) || 0);


function Block({ title, children }: { title: string; children: ReactNode }) {
  return <section className="mt-4 break-inside-avoid"><h3 className="mb-1 border-b-2 border-[#003865] pb-0.5 text-[11.5px] font-bold uppercase tracking-wide text-[#003865]">{title}</h3><div className="text-[11.5px] leading-[17px]">{children}</div></section>;
}

function Rows({ rows }: { rows: [string, ReactNode][] }) {
  return <table className="w-full border-collapse text-[11px]"><tbody>{rows.map(([label, value]) => <tr key={label}><td className="w-[42%] border border-[#c6d6e1] bg-[#f3f7fa] px-2 py-1 font-semibold">{label}</td><td className="border border-[#c6d6e1] px-2 py-1">{value}</td></tr>)}</tbody></table>;
}

function Coverages({ policy }: { policy: PolicyRecord }) {
  return <>
    {policy.units.map((unit, index) => <div key={index} className="mb-2 break-inside-avoid"><div className="font-bold">{index + 1}. {unit.label}{unit.idNumber ? ` · ${policy.product === 'boat' ? 'HIN' : 'VIN'} ${unit.idNumber}` : ''}</div>{unit.details.length > 0 && <div className="text-[10px] text-[#52616c]">{unit.details.join(' · ')}</div>}
      {unit.coverages.length > 0 && <table className="mt-1 w-full border-collapse text-[10.5px]"><thead><tr className="bg-[#e3edf4] text-left"><th className="border border-[#c6d6e1] px-2 py-1">Coverage</th><th className="border border-[#c6d6e1] px-2 py-1">Limit / Deductible</th><th className="border border-[#c6d6e1] px-2 py-1 text-right">Premium</th></tr></thead><tbody>{unit.coverages.map((line) => <tr key={line.label}><td className="border border-[#c6d6e1] px-2 py-1">{line.label}</td><td className="border border-[#c6d6e1] px-2 py-1">{line.value}</td><td className="border border-[#c6d6e1] px-2 py-1 text-right tabular-nums">{line.premium ? money(line.premium) : '—'}</td></tr>)}</tbody></table>}
    </div>)}
    {policy.policyCoverages.length > 0 && <Rows rows={policy.policyCoverages.map((line) => [line.label, `${line.value}${line.premium ? ` · ${money(line.premium)}` : ''}`])} />}
  </>;
}

function IdCards({ policy }: { policy: PolicyRecord }) {
  const auto = policy.product === 'auto';
  return <div className="grid grid-cols-2 gap-3">{policy.units.flatMap((unit, index) => [0, 1].map((copy) => <div key={`${index}-${copy}`} className="break-inside-avoid rounded-[4px] border-2 border-[#003865] p-3 text-[10.5px] leading-[15px]">
    <div className="mb-1 flex justify-between text-[9px] font-bold uppercase text-[#003865]"><span>{auto ? rulesFor(policy.state).idCardTitle : 'Insurance Identification Card'}</span><span>{copy === 0 ? 'Keep in vehicle' : 'Customer copy'}</span></div>
    <div className="mb-1 rounded-[2px] bg-[#fde8ea] px-1 text-center text-[8.5px] font-bold text-[#c8102e]">TRAINING SIMULATION ONLY. NOT PROOF OF INSURANCE.</div>
    <div className="flex items-start justify-between gap-2"><div className="font-bold">Training Insurance Company (simulation)</div><img src={LOGO_URL} alt="LAVA" className="h-[16px] w-auto shrink-0" /></div>
    <div>Policy #: <b>{policy.policyNumber}</b></div>
    <div>Effective {policy.effectiveDate} · Expires {policy.expirationDate}</div>
    <div>Named insured: <b>{policy.insured.name}</b></div>
    <div>{policy.insured.street}, {policy.insured.cityStateZip}</div>
    <div className="mt-1 font-bold">{unit.label}</div>
    {unit.idNumber && <div>{policy.product === 'boat' ? 'HIN' : 'VIN'}: {unit.idNumber}</div>}
    <div className="mt-1 text-[9px] text-[#52616c]">Agent: {policy.agentName} · {policy.agentCode}</div>
    {auto && <div className="mt-1 text-[8.5px] leading-[11px] text-[#52616c]">{rulesFor(policy.state).statuteText}</div>}
    <div className="mt-1 text-[9px] font-bold text-[#003865]">Report a claim 24/7: {CLAIMS_LINE} (training line)</div>
  </div>))}</div>;
}

function DeclarationsBody({ policy }: { policy: PolicyRecord }) {
  return <>
    <Block title="Policy information"><Rows rows={[['Policy number', policy.policyNumber], ['Product', policy.productName], ['Policy period', `${policy.effectiveDate} to ${policy.expirationDate} (12:01 a.m. standard time)`], ['Term', `${policy.termNumber} (${policy.termMonths} months)`], ['Bill plan', policy.billPlanName], ['Total policy premium', money(policy.termPremium)], ['Agent', `${policy.agentName} · ${policy.agentCode}`]]} /></Block>
    <Block title="Named insured"><Rows rows={[['Name', policy.insured.name], ['Mailing address', `${policy.insured.street}, ${policy.insured.cityStateZip}`], ...(policy.drivers.length ? [['Rated drivers/operators', policy.drivers.join(', ')] as [string, string]] : [])]} /></Block>
    <Block title="Coverages and premium"><Coverages policy={policy} /></Block>
    <Block title="Discounts">{policy.discounts.length ? policy.discounts.join(' · ') : 'None'}</Block>
  </>;
}

function DocumentBody({ policy, document }: { policy: PolicyRecord; document: PolicyDocument }) {
  const data = document.data;
  const rules = rulesFor(policy.state);
  const nonpayment = data.kind === 'nonpayment';
  switch (document.type) {
    case 'Declarations':
    case 'Renewal Declarations':
      return <DeclarationsBody policy={policy} />;
    case 'Policy Packet':
      return <>
        <Block title="Policy packet"><Rows rows={[['Copy', String(data.copy)], ['Issued', document.date], ['Contents', ['Declarations Page', ...(['auto', 'motorcycle', 'motorhome', 'trailer', 'commercialAuto'].includes(policy.product) && data.copy !== 'Lienholder Copy' ? ['Insurance Identification Cards'] : []), ...(data.copy !== 'Lienholder Copy' ? ['Application for Insurance (summary)'] : [])].join(' · ')]]} /></Block>
        <DeclarationsBody policy={policy} />
      </>;
    case 'ID Cards':
      return <Block title="Identification cards"><IdCards policy={policy} /></Block>;
    case 'Application':
      return <>
        <Block title="Application summary"><Rows rows={[['Applicant', policy.insured.name], ['Date of birth', policy.insured.dob], ['Product', policy.productName], ['Requested effective date', policy.effectiveDate], ['Document delivery', String(data.delivery || '—')], ['e-Signature status', policy.esign]]} /></Block>
        <Block title="Applicant statement">I have read this application and the statements in it are true to the best of my knowledge. I understand the policy may be void if any material information is misrepresented.</Block>
        <section className="mt-6 grid grid-cols-2 gap-8 text-[10px] text-[#52616c]"><div className="border-t border-[#28343c] pt-1">{policy.esign === 'Signed' ? `e-Signed by ${policy.insured.name}` : 'Applicant signature / date'}</div><div className="border-t border-[#28343c] pt-1">Producer signature / date</div></section>
      </>;
    case 'FS-1 Certificate of Insurance':
      return <Block title="North Carolina Form FS-1">
        <p className="mb-2">This certifies that the insurer named below has issued a motor vehicle liability policy that meets the requirements of North Carolina financial responsibility law for the vehicle(s) listed. Reason for filing: <b>{String(data.reason || 'New business')}</b>.</p>
        <Rows rows={[['Insurer', 'Progressive (training simulation)'], ['Policy number', policy.policyNumber], ['Effective date', policy.effectiveDate], ['Expiration date', policy.expirationDate], ['Owner / named insured', `${policy.insured.name}, ${policy.insured.street}, ${policy.insured.cityStateZip}`], ['Vehicle(s)', policy.units.map((unit) => `${unit.label}${unit.idNumber ? ` (VIN ${unit.idNumber})` : ''}`).join('; ')]]} />
      </Block>;
    case 'Billing Statement':
      return <Block title="Statement"><Rows rows={[['Installment', `#${data.installment}`], ['Amount due', money(data.amount)], ['Due date', String(data.due)], ['Payment method', data.autopay === 'Yes' ? `Automatic payment (${policy.paymentMethod}). No action needed.` : 'Pay online, by phone or by mail']]} /><p className="mt-2 text-[10.5px]">Payments received more than 2 days after the due date are charged a {money(LATE_FEE)} late fee. Unpaid balances may result in a notice of cancellation.</p></Block>;
    case 'Payment Receipt':
      return <Block title="Payment received"><Rows rows={[['Amount', money(data.amount)], ['Method', String(data.method)], ['Confirmation #', String(data.confirmation)], ['Date', document.date]]} /></Block>;
    case 'Notice of Cancellation':
      return <>
        <Block title="Notice"><p>Your policy will be cancelled effective <b>{String(data.effectiveDate)} at 12:01 a.m.</b></p><p className="mt-1">Reason for cancellation: <b>{String(data.reason)}</b></p>
          {nonpayment && <p className="mt-1">To keep your coverage, pay <b>{money(data.amountDue)}</b> so that it is received before the cancellation effective date. If payment is received in time, this notice is rescinded and coverage continues with no lapse.</p>}
          <p className="mt-1 text-[10.5px] text-[#52616c]">Notice period: {nonpayment ? `${rules.nonpaymentNoticeDays} days (nonpayment of premium)` : `at least ${rules.otherNoticeDays} days`}, as required by {rules.name === 'North Carolina' ? 'N.C. Gen. Stat. § 58-36-85' : `${rules.name} law`}. Mailed by first-class mail to your last known address.</p></Block>
        {rules.name === 'North Carolina'
          ? <Block title="Important information required by North Carolina law"><p>Operating a motor vehicle without the financial responsibility required by Article 13 of Chapter 20 of the North Carolina General Statutes may result in fines, loss of your vehicle registration plates and other penalties.</p><p className="mt-1">You have the right to request a review of this termination by the North Carolina Department of Insurance. Your written request must be filed within 10 days after you receive this notice.</p></Block>
          : <Block title={`Important information for ${rules.name} drivers`}><p>{rules.insuranceRequired ? `${rules.name} requires insurance on registered vehicles. ` : ''}{rules.plateSurrender ? `If coverage ends, surrender the plate at ${rules.plateSurrender.agency} or replace the coverage first; otherwise ${rules.plateSurrender.consequence}` : 'Make sure replacement coverage is in place before this date.'}</p><p className="mt-1">Questions about this notice can be directed to your agent or the {rules.name} Department of Insurance.</p></Block>}
      </>;
    case 'Cancellation Confirmation':
      return <Block title="Cancellation"><Rows rows={[['Effective date', `${String(data.effectiveDate)} 12:01 a.m.`], ['Reason', String(data.reason)], ['Requested by', data.kind === 'insured' ? 'Named insured' : data.kind === 'company' ? 'Company (underwriting)' : 'Company (nonpayment)'], ['Refund method', String(data.method)], ['Premium earned', money(data.earned)], ['Payments received', money(data.paid)], [Number(data.refund) > 0 ? 'Refund due to you' : 'Balance due', money(Number(data.refund) > 0 ? data.refund : data.balanceDue)]]} /><p className="mt-2 text-[10.5px]">{Number(data.refund) > 0 ? 'Refunds are returned to the original payment method within 7 to 14 business days.' : Number(data.balanceDue) > 0 ? 'Earned premium not paid may be referred to collections.' : ''} The North Carolina DMV has been notified that this coverage ended.</p></Block>;
    case 'Rescission of Cancellation':
      return <Block title="Your coverage continues">We received your payment. The notice of cancellation previously mailed is rescinded, and your policy continues with no lapse in coverage.</Block>;
    case 'Reinstatement Notice':
      return <Block title="Policy reinstated"><p>Your policy has been reinstated effective {document.date}.</p>{data.lapseFrom ? <p className="mt-1 font-bold text-[#c8102e]">There was no coverage in force from {String(data.lapseFrom)} through {String(data.lapseTo)}. Any loss during that period is not covered.</p> : <p className="mt-1">Coverage was reinstated with no lapse.</p>}{Number(data.amount) > 0 && <p className="mt-1">Amount collected to reinstate: {money(data.amount)}.</p>}</Block>;
    case 'Renewal Offer':
      return <>
        <Block title="Renewal offer"><Rows rows={[['Renewal policy period', `${String(data.effectiveDate)} to ${String(data.expirationDate)}`], ['Current term premium', money(data.previousPremium)], ['Renewal premium', money(data.premium)], ['Change', `${(((Number(data.premium) - Number(data.previousPremium)) / Math.max(1, Number(data.previousPremium))) * 100).toFixed(1)}%`], ['Bill plan', String(data.plan)], ['Due to renew', policy.autopay ? `Drafted automatically on ${String(data.effectiveDate)}` : `${money(data.dueToday)} by ${String(data.effectiveDate)}`]]} /></Block>
        <Block title="Why your premium changed"><ul className="list-disc pl-5">{(policy.renewal?.reasons ?? ['Rate review at renewal']).map((reason) => <li key={reason}>{reason}</li>)}</ul></Block>
      </>;
    case 'Non-Renewal Notice':
      return data.by === 'company'
        ? <Block title="Notice of non-renewal"><p>Your policy will not be renewed and coverage ends at 12:01 a.m. on <b>{String(data.expirationDate)}</b>.</p><p className="mt-1">Reason: <b>{String(data.reason)}</b></p><p className="mt-1 text-[10.5px] text-[#52616c]">This notice is mailed at least {rules.otherNoticeDays} days before expiration as required by {rules.name === 'North Carolina' ? 'N.C. Gen. Stat. § 58-36-85' : `${rules.name} law`}.{rules.name === 'North Carolina' ? ' You have the right to request review by the North Carolina Department of Insurance within 10 days of receiving this notice.' : ` Questions can be directed to the ${rules.name} Department of Insurance.`}</p></Block>
        : <Block title="Non-renewal confirmation">As you requested, this policy will not renew. Coverage ends at 12:01 a.m. on <b>{String(data.expirationDate)}</b>. Make sure replacement coverage is in place by that date.</Block>;
    case 'Expiration Notice':
      return <Block title="Coverage ended">Your policy expired on {policy.expirationDate}. Reason: {String(data.reason)}. {rules.reporting ? `${rules.reporting.system} has been notified that coverage ended. ` : ''}Contact your agent to start a new policy.</Block>;
    case 'Bill Plan Change Confirmation':
      return <Block title="Bill plan changed"><Rows rows={[['New bill plan', String(data.plan)], ['Remaining payments', String(data.remaining)], ['Installment fee per payment', money(data.fee)]]} /></Block>;
    case 'Returned Payment Notice':
      return <Block title="Payment returned">Your payment of {money(data.amount)} was returned by your bank. A returned payment fee of {money(data.fee)} was charged. A notice of cancellation for nonpayment has been issued; pay the amount due to keep your coverage.</Block>;
    case 'Amended Declarations':
      return <>
        <Block title="Policy change"><Rows rows={[['Policy number', policy.policyNumber], ['Change effective date', String(data.changeEffective)], ['Changes made', String(data.changes)], [Number(data.prorated) < 0 ? 'Return premium' : 'Additional premium', money(Math.abs(Number(data.prorated)))], ['Revised total policy premium', money(policy.termPremium)], ['Policy period', `${policy.effectiveDate} to ${policy.expirationDate}`]]} /></Block>
        <Block title="Named insured"><Rows rows={[['Name', policy.insured.name], ['Mailing address', `${policy.insured.street}, ${policy.insured.cityStateZip}`], ...(policy.drivers.length ? [['Rated drivers/operators', policy.drivers.join(', ')] as [string, string]] : [])]} /></Block>
        <Block title="Coverages after this change"><Coverages policy={policy} /></Block>
        {policy.lienholders.length > 0 && <Block title="Lienholders / additional interests"><Rows rows={policy.lienholders.map((holder) => [`${holder.kind} · ${holder.unit}`, `${holder.name}, ${holder.address}${holder.loanNumber ? ` · Loan #${holder.loanNumber}` : ''}`])} /></Block>}
        <p className="mt-3 text-[10.5px] text-[#52616c]">These amended declarations replace any declarations issued earlier for this policy period. All other terms and conditions are unchanged.</p>
      </>;
    case 'Evidence of Insurance':
      return <>
        <Block title="Evidence of insurance: lienholder copy"><Rows rows={[['Issued to', `${String(data.name)}, ${String(data.address)}`], ['Interest', String(data.kind)], ['Loan / account number', String(data.loanNumber || '—')], ['Covered unit', String(data.unit)], ['Named insured', policy.insured.name], ['Policy number', policy.policyNumber], ['Policy period', `${policy.effectiveDate} to ${policy.expirationDate}`]]} /></Block>
        <Block title="Physical damage coverage"><Rows rows={(policy.units.find((unit) => unit.label === data.unit)?.coverages ?? []).filter((line) => !/bodily|liability/i.test(line.label) && /collision|comprehensive|other than|physical|property|contents|hull/i.test(line.label)).map((line) => [line.label, line.value] as [string, string])} /></Block>
        <p className="mt-3 text-[10.5px] text-[#52616c]">The named {String(data.kind).toLowerCase()} is listed as loss payee. The insurer will give the {String(data.kind).toLowerCase()} 10 days written notice of cancellation.</p>
      </>;
    case 'Certificate of Insurance':
      return <>
        <p className="mb-2 text-[10.5px] font-bold text-[#52616c]">This certificate is issued as a matter of information only and confers no rights upon the certificate holder. It does not amend, extend or alter the coverage afforded by the policy.</p>
        <Block title="Insured"><Rows rows={[['Business name', policy.insured.name], ['Address', `${policy.insured.street}, ${policy.insured.cityStateZip}`], ['Producer', `${policy.agentName} · ${policy.agentCode}`]]} /></Block>
        <Block title="Coverages"><Rows rows={[['Type of insurance', policy.productName], ['Policy number', policy.policyNumber], ['Policy effective / expiration', `${policy.effectiveDate} / ${policy.expirationDate}`], ...policy.policyCoverages.map((line) => [line.label, line.value] as [string, string]), ...policy.units.flatMap((unit) => unit.coverages.slice(0, 3).map((line) => [`${unit.label}: ${line.label}`, line.value] as [string, string]))]} /></Block>
        <Block title="Certificate holder">{String(data.holder || 'Evidence of coverage (to whom it may concern)')}</Block>
        <Block title="Cancellation">Should any of the above policies be cancelled before the expiration date, notice will be delivered in accordance with the policy provisions.</Block>
      </>;
  }
}

export function PolicyDocumentSheet({ policy, document }: { policy: PolicyRecord; document: PolicyDocument }) {
  return <article className="print-area relative mx-auto max-w-[800px] overflow-hidden rounded border border-[#c6d6e1] bg-white px-8 py-6 text-[#28343c] shadow-sm print:max-w-none print:border-0 print:p-0 print:shadow-none">
    <div aria-hidden className="pointer-events-none absolute inset-0 flex items-center justify-center"><span className="-rotate-[24deg] whitespace-nowrap text-[54px] font-black uppercase tracking-widest text-[#003865]/[.05]">Training Simulation</span></div>
    <header className="flex items-start justify-between border-b-4 border-[#003865] pb-3">
      <div><div className="flex items-center gap-3"><img src={LOGO_URL} alt="LAVA" className="h-[30px] w-auto" /><span className="h-[26px] w-px bg-[#c6d6e1]" aria-hidden /><span className="text-[18px] font-light tracking-[-.5px] text-[#003865]">FOR<b>AGENTS</b>ONLY</span></div><div className="mt-1 text-[10px] text-[#52616c]">{policy.insured.name} · {policy.insured.street}, {policy.insured.cityStateZip}</div></div>
      <div className="text-right"><h2 className="text-[17px] font-bold text-[#003865]">{DOCUMENT_TITLES[document.type]}</h2><div className="text-[10px] text-[#52616c]">{policy.productName} Policy #{policy.policyNumber} · Term {document.term}</div><div className="text-[10px] text-[#52616c]">Date: {document.date}</div></div>
    </header>
    <p className="mt-2 rounded bg-[#fdf0f1] px-2 py-1 text-center text-[9px] font-bold uppercase tracking-wide text-[#c8102e]">Training simulation only. Not a valid insurance document or proof of coverage.</p>
    <DocumentBody policy={policy} document={document} />
  </article>;
}

/** Full-screen preview; only the document prints while it is open (see index.css). */
const PDF_TYPES: PolicyDocument['type'][] = ['Declarations', 'Renewal Declarations', 'Amended Declarations', 'Policy Packet'];

export function DocumentPreview({ policy, document, onClose }: { policy: PolicyRecord; document: PolicyDocument; onClose: () => void }) {
  return createPortal(<div className="print-portal fixed inset-0 z-[90] overflow-y-auto bg-[#1b2a36]/70 px-4 pb-10 pt-[20px]">
    <div className="no-print sticky top-0 z-10 mx-auto mb-[14px] flex max-w-[800px] items-center justify-between rounded-[3px] bg-[#003865] px-[16px] py-[10px] text-white shadow-lg"><span className="text-[14px] font-bold">{DOCUMENT_TITLES[document.type]} · {document.date}</span><span className="flex items-center gap-[10px]">{PDF_TYPES.includes(document.type) && <button type="button" onClick={() => (document.type === 'Policy Packet' ? downloadPolicyPacket(policy, String(document.data.copy) as PacketCopy) : downloadDeclarationsPdf(policy, DOCUMENT_TITLES[document.type]))} className="flex h-[34px] items-center gap-2 rounded-[3px] bg-[#e87722] px-[14px] text-[12px] font-bold uppercase text-white hover:bg-[#cf6512]"><Download size={15} />Download PDF</button>}<button type="button" onClick={() => { notify({ kind: 'document', title: `${DOCUMENT_TITLES[document.type]} printed`, detail: `${policy.productName} #${policy.policyNumber} · ${policy.insured.name}.`, target: { view: 'policy', policyId: policy.id } }); window.print(); }} className="flex h-[34px] items-center gap-2 rounded-[3px] bg-white px-[14px] text-[12px] font-bold uppercase text-[#003865]"><Printer size={15} />Print / Save as PDF</button><button type="button" aria-label="Close preview" onClick={onClose} className="rounded p-1"><X size={20} /></button></span></div>
    <PolicyDocumentSheet policy={policy} document={document} />
  </div>, window.document.body);
}
