import { useState, type FormEvent, type ReactNode } from 'react';
import { useQuote } from '@/context/useQuote';
import { Bell, Bookmark, ChevronDown, CircleHelp, FileText, Menu, Plus, RotateCcw, Search, UserRound, X } from 'lucide-react';

type AlertItem = { text: string; link?: boolean };
type AlertSection = { title: string; items: AlertItem[] };
const navItems = ['New Business', 'Prospecting', 'Manage Policies', 'Products', 'Agency Admin', 'News', 'Support'];
const alertSections: AlertSection[] = [
  { title: 'Admin Alerts', items: [{ text: 'Commission statement will be avail.: 9/5' }] },
  { title: 'Customer Communication Alerts', items: [{ text: 'Billing reminders', link: true }] },
  { title: 'Policy Level Alerts', items: [{ text: 'e-Sign follow-up required: 11', link: true }, { text: 'Policies require follow up: 1', link: true }, { text: 'Policies pending cancel or renewal', link: true }, { text: 'Save canceled or expired policies: 4', link: true }, { text: 'Policies pending paperless enrollment: 1', link: true }] },
  { title: 'New Business & Prospecting', items: [{ text: 'Requote prospects: Sep.', link: true }] },
  { title: 'Claims Alerts', items: [{ text: 'Recent claims: 2', link: true }] },
  { title: 'Customer Endorsements and PGR ReWrites', items: [{ text: 'Customer policy changes: 4', link: true }, { text: 'PGR rewrites/quotes: 1', link: true }] },
];

function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className="bg-[#003865] text-white shadow-sm">
    <div className="mx-auto flex min-h-[50px] max-w-[1440px] items-center gap-5 px-4">
      <div className="flex shrink-0 items-center gap-2"><button className="rounded p-1 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open navigation"><Menu size={20} /></button><div className="whitespace-nowrap text-[17px] font-light tracking-[-.6px]">FOR<span className="font-bold">AGENTS</span>ONLY</div></div>
      <nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-[50px] z-20 flex-col bg-[#003865] px-5 pb-4 md:static md:flex md:flex-row md:items-center md:gap-5 md:p-0`}>{navItems.map((item) => <button key={item} className="flex items-center justify-between gap-1 border-b border-white/10 py-2 text-left text-[11px] font-semibold whitespace-nowrap hover:text-[#f5a45d] md:border-0 md:py-0">{item}<ChevronDown size={12} /></button>)}</nav>
      <div className="ml-auto flex shrink-0 items-center gap-3"><Bookmark size={18} fill="currentColor" className="hidden sm:block" /><span className="relative hidden sm:block"><Bell size={18} /><i className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-[#f5a45d]" /></span><UserRound size={19} fill="white" className="hidden sm:block" /><AgentGreeting /></div>
    </div>
  </header>;
}

/** "Hello, [agent]" with a small profile editor: the logged-in agent is a session value, never reference data. */
function AgentGreeting() {
  const { state, updateAgent } = useQuote();
  const { agent } = state;
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState(agent);
  const field = (key: keyof typeof agent, label: string) => <label className="block text-[10px] font-bold text-[#003865]">{label}<input value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: key === 'agencyCode' ? event.target.value.toUpperCase().slice(0, 8) : event.target.value })} className="mt-0.5 h-[24px] w-full rounded-[2px] border border-[#8194a5] px-2 text-[11px] font-normal text-[#28343c] outline-none focus:border-[#0073cf]" /></label>;
  return <div className="relative text-right text-[10px] font-semibold leading-[1.15]"><div>Hello, {agent.name}</div><button type="button" aria-expanded={open} onClick={() => { setDraft(agent); setOpen(!open); }} className="flex items-center gap-1 whitespace-nowrap text-[9px] font-normal hover:text-[#f5a45d]">{agent.agencyName} ({agent.agencyCode}) <ChevronDown size={11} /></button>
    {open && <form onSubmit={(event) => { event.preventDefault(); if (draft.name.trim() && draft.agencyName.trim() && draft.agencyCode.trim()) { updateAgent({ name: draft.name.trim(), agencyName: draft.agencyName.trim(), agencyCode: draft.agencyCode.trim() }); setOpen(false); } }} className="absolute right-0 top-[30px] z-30 w-[220px] space-y-2 rounded-[3px] border border-[#a6adb3] bg-white p-3 text-left shadow-lg">
      <div className="text-[11px] font-bold text-[#003865]">Signed-in agent</div>
      {field('name', 'Agent name')}{field('agencyName', 'Agency name')}{field('agencyCode', 'Producer code')}
      <div className="flex justify-end gap-1 pt-1"><button type="button" onClick={() => setOpen(false)} className="bg-[#003865] px-2 py-1 text-[9px] font-bold text-white">CANCEL</button><button type="submit" className="bg-[#0073cf] px-2 py-1 text-[9px] font-bold text-white">SAVE</button></div>
    </form>}
  </div>;
}

function SearchBar() {
  const agentCode = useQuote().state.agent.agencyCode;
  const [searched, setSearched] = useState(false);
  const [values, setValues] = useState({ last: '', first: '', product: 'All', status: 'Active Policies', agent: 'All' });
  const setValue = (field: keyof typeof values, value: string) => { setValues((current) => ({ ...current, [field]: value })); setSearched(false); };
  const reset = () => { setValues({ last: '', first: '', product: 'All', status: 'Active Policies', agent: 'All' }); setSearched(false); };
  return <div className="border-b border-[#a8b0b8] bg-[#f3f4f6] px-4 py-2"><form onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSearched(true); }} className="mx-auto flex max-w-[1440px] flex-wrap items-end gap-x-2 gap-y-1 text-[10px] text-[#003865]"><div className="flex flex-col gap-1 pr-1 font-semibold"><label className="flex items-center gap-1"><input type="radio" name="search" defaultChecked className="accent-[#0073cf]" /> Customer</label><label className="flex items-center gap-1"><input type="radio" name="search" className="accent-[#0073cf]" /> Policy</label></div><SearchField label="Last Name" value={values.last} onChange={(value) => setValue('last', value)} /><SearchField label="First Name" value={values.first} onChange={(value) => setValue('first', value)} /><SelectField label="Products" value={values.product} options={['All', 'Auto', 'Home', 'Life']} onChange={(value) => setValue('product', value)} /><SelectField label="Policy Status" value={values.status} options={['Active Policies', 'All Policies', 'Pending']} onChange={(value) => setValue('status', value)} /><SelectField label="Agent Codes" value={values.agent} options={['All', agentCode]} onChange={(value) => setValue('agent', value)} /><div className="flex items-end gap-1 pb-0.5"><button type="submit" className="flex h-[18px] min-w-[105px] items-center justify-center gap-1 bg-[#0073cf] px-3 text-[10px] font-bold text-white hover:bg-[#005da8]"><Search size={11} /> Search</button><button type="button" onClick={reset} className="flex h-[18px] min-w-[68px] items-center justify-center gap-1 bg-[#003865] px-3 text-[10px] font-bold text-white hover:bg-[#002746]"><RotateCcw size={10} /> Reset</button></div>{searched && <span className="pb-1 text-[#0073cf]">Search ready</span>}</form></div>;
}
function SearchField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex flex-col gap-1 font-bold"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} className="h-[18px] w-[160px] rounded-[2px] border border-[#8194a5] bg-white px-2 text-[10px] font-normal outline-none focus:border-[#0073cf]" /></label>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="flex flex-col gap-1 font-bold"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-[18px] w-[115px] rounded-[2px] border border-[#8194a5] bg-white px-1 text-[10px] font-normal outline-none focus:border-[#0073cf]">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }

type QuoteActions = { onSelect: () => void; onOpenExisting: () => void; existingQuote: string };
function QuoteCard({ onSelect, onOpenExisting, existingQuote }: QuoteActions) {
  const [activeTab, setActiveTab] = useState<'new' | 'existing'>('new');
  return <section className="overflow-hidden rounded-[3px] border border-[#a6adb3] bg-white"><div className="flex h-[35px] border-b border-[#a6adb3] bg-[#f0f0ee]"><button onClick={() => setActiveTab('new')} className={`flex-1 border-r border-[#a6adb3] px-2 text-[14px] font-bold ${activeTab === 'new' ? 'bg-white text-[#003865]' : 'text-[#003865]/80'}`}>New Quote</button><button onClick={() => setActiveTab('existing')} className={`flex-1 px-2 text-[14px] font-bold ${activeTab === 'existing' ? 'bg-white text-[#003865]' : 'text-[#003865]/80'}`}>Existing Quote</button></div><div className="grid grid-cols-[50px_1fr] items-center gap-2 p-3 text-[10px] text-[#003865]"><span className="font-bold">{activeTab === 'new' ? 'State' : 'Quote'}</span><select className="h-[27px] rounded border border-[#cbd5df] bg-white px-2 text-[11px] text-[#7b8995]"><option>{activeTab === 'new' ? 'North Carolina' : existingQuote || 'Find existing quote'}</option></select><span /><button onClick={activeTab === 'new' ? onSelect : onOpenExisting} disabled={activeTab === 'existing' && !existingQuote} className="h-[32px] rounded border-2 border-[#f26722] bg-[#003865] text-[14px] font-bold text-white shadow-[0_0_0_1px_#0073cf] hover:bg-[#005081]">{activeTab === 'new' ? 'Select Product(s)' : 'Open Quote'}</button></div></section>;
}
function LeftColumn(quoteActions: QuoteActions) {
  const [showId, setShowId] = useState(true);
  return <aside className="space-y-4"><QuoteCard {...quoteActions} /><div className="relative overflow-hidden rounded-[3px] bg-[#087dc1] px-3 py-3 text-center text-white shadow-sm"><div className="absolute -left-4 top-0 h-full w-1/2 -skew-x-12 bg-white/10" /><div className="relative"><div className="text-[15px] font-bold">Training Center</div><p className="mt-1 text-[11px] font-semibold">Access all of our training pages here.</p></div></div>{showId && <div className="relative border border-[#003865] bg-white px-8 py-4 text-center text-[#101820] shadow-sm"><button onClick={() => setShowId(false)} aria-label="Dismiss unique ID" className="absolute right-1.5 top-1 text-[#003865] hover:text-[#e87722]"><X size={17} /></button><h2 className="text-[25px] font-bold tracking-[-1px] text-[#003865]">Unique ID<sup className="ml-1 text-[10px]">®</sup></h2><p className="mt-3 text-[11px] font-bold leading-[1.45]">There is not a producer number assigned to your Unique ID. If you have an active appointment with us, please add it now for the most personalized experience on FAO.</p><button className="mt-4 text-[11px] font-bold text-[#003865] underline decoration-[#e87722] decoration-2 underline-offset-2 hover:text-[#0073cf]">Add Producer Number</button></div>}<div className="relative overflow-hidden border border-[#a5c8d8] bg-[#dbf3fc] px-3 py-3 text-[#1d5e80] shadow-sm"><div className="flex items-start justify-between text-[20px] leading-[1.1]"><div>Product Guides and<br />Reference Cards</div><Plus size={20} /></div><div className="mt-4 space-y-2 text-[10px] font-bold"><div>State</div><select className="h-[25px] w-full border border-[#93b7c9] bg-white px-2 text-[10px]"><option>North Carolina</option></select><div>Product</div><select className="h-[25px] w-full border border-[#93b7c9] bg-white px-2 text-[10px]"><option>Select Product</option></select></div></div></aside>;
}
function AlertsPanel() { return <section className="min-w-0"><div className="flex items-center justify-between bg-[#087dc1] px-2 py-1.5 text-white"><h1 className="text-[15px] font-bold">SmartView<sup className="text-[8px]">®</sup> Alerts</h1><a href="#alerts-help" className="flex items-center gap-1 text-[11px] font-bold underline"><CircleHelp size={13} /> What are SmartView<sup className="text-[7px]">®</sup> Alerts?</a></div><div className="space-y-1.5 bg-white p-1.5">{alertSections.map((section) => <div key={section.title} className="border border-[#b9bcb9]"><div className="px-2 pb-0.5 pt-1.5 text-[11px] font-bold text-[#003865]">{section.title}</div><div className="grid grid-cols-1 gap-[3px] bg-white p-[3px] sm:grid-cols-2">{[...section.items, ...(section.items.length % 2 ? [{ text: '' }] : [])].map((item, index) => item.link ? <a key={item.text} href={`#${item.text.replace(/ /g, '-').toLowerCase()}`} className="min-h-[26px] bg-[#f3f2ed] px-2 py-[5px] text-[11px] font-bold text-[#003865] underline decoration-[#003865] underline-offset-2 hover:text-[#0073cf]">{item.text}</a> : <span key={item.text || `empty-${index}`} className="min-h-[26px] bg-[#f3f2ed] px-2 py-[5px] text-[11px] text-[#28343c]">{item.text}</span>)}</div></div>)}</div></section>; }
function PartnershipCard() { return <section className="bg-[#f2f2f2] px-4 pb-3 pt-3 text-center text-[#003865] shadow-sm"><div className="mx-auto w-fit border border-[#72b0d1] px-2 py-0.5 text-[8px] tracking-[3px] text-[#087dc1]">PATHS TO<br /><strong className="text-[20px] tracking-[2px]">PARTNERSHIP</strong></div><div className="mt-4 text-[15px] font-bold">INVESTMENT TIER</div><Gauge value="135" /><div className="mt-1 grid grid-cols-3 gap-1.5"><StatBox number="33" label={<>NO PROOF<br />OF PRIOR</>} /><StatBox number="72" label={<>PROOF<br />OF PRIOR</>} /><StatBox number="30" label={<>SAFE DRIVER<br />&amp; HOMEOWNER</>} /></div></section>; }
// Segmented horseshoe gauge: three dark tiers and one light tier, open at the bottom.
const GAUGE_R = 47;
const GAUGE_C = 2 * Math.PI * GAUGE_R;
const GAUGE_SWEEP = 0.75;
const gaugeSegments: [number, number, string][] = [[0, 0.31, '#345876'], [0.32, 0.58, '#345876'], [0.59, 0.78, '#345876'], [0.79, 1, '#dfe5eb']];
function Gauge({ value }: { value: string }) { return <div className="relative mx-auto mt-1 h-[143px] w-[143px]"><svg viewBox="0 0 120 120" className="h-full w-full rotate-[135deg]">{gaugeSegments.map(([from, to, color]) => <circle key={from} cx="60" cy="60" r={GAUGE_R} fill="none" stroke={color} strokeWidth="17" strokeDasharray={`${(to - from) * GAUGE_SWEEP * GAUGE_C} ${GAUGE_C}`} strokeDashoffset={-from * GAUGE_SWEEP * GAUGE_C} />)}</svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="-mt-1 text-[32px] font-bold leading-none text-[#345876]">{value}</span><span className="mt-[34px] w-[78px] text-[6.5px] font-bold leading-[1.2]">CURRENT TOTAL AUTO<br />POLICIES IN FORCE</span></div></div>; }
function StatBox({ number, label }: { number: string; label: ReactNode }) { return <div className="rounded-[2px] bg-[#345876] px-1 py-1.5 text-white"><div className="text-[21px] font-bold leading-none">{number}</div><div className="mt-1 text-[7px] font-bold leading-[1.15]">{label}</div></div>; }
function BottomStats() { return <div className="flex items-center justify-between gap-2 px-2 pt-4 text-[#003865]"><div className="w-[96px] text-center text-[11px] font-bold leading-[1.35]">TOTAL ACCOUNT<br />POLICIES IN<br />FORCE</div><div className="relative h-[108px] w-[108px] shrink-0"><svg viewBox="0 0 120 120" className="h-full w-full -rotate-90"><circle cx="60" cy="60" r="43" fill="none" stroke="#d2d2d2" strokeWidth="14" /><circle cx="60" cy="60" r="43" fill="none" stroke="#f47721" strokeWidth="14" strokeDasharray="73 270" /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-[17px] font-bold">135</span><span className="text-[8px] font-bold">OF 499</span></div></div></div>; }
function AgencyNews() { return <section className="text-[#003865]"><h2 className="mb-3 text-[25px] font-light tracking-[-.5px]">Your Agency News</h2><article className="border border-[#b9bcb9] bg-white px-3 py-3 text-[11px] leading-[1.35] shadow-sm"><h3 className="font-bold">Exciting changes coming to FAO on January 22!</h3><p className="mt-1">We're happy to announce some important updates to ForAgentsOnly.com (FAO), available on January 22, 2026. These enhancements are designed to empower agents with greater control over licensing requests and streamline processes.</p><button className="mt-2 font-bold underline decoration-[#e87722] underline-offset-2 hover:text-[#0073cf]">Read more</button></article><article className="mt-2 border border-[#b9bcb9] bg-white px-3 py-3 text-[11px] leading-[1.35] shadow-sm"><h3 className="font-bold">The latest news and resources for your agency</h3><p className="mt-1">Find helpful tools, announcements, and updates created to support your agency.</p></article></section>; }


// Page-level notice the portal shows while products are being selected (it sits under the modal overlay).
function BindingBanner() { return <div className="bg-[#1d252b] px-3 py-[3px] text-[11px] text-white"><span className="text-[13px]">Binding Restrictions:</span> Due to wildfires in multiple states writing new business, making endorsements, or changing limits on existing policies may be unavailable in affected areas. <a href="#restrictions" className="font-bold underline">Read more</a></div>; }

export function Dashboard({ onSelectProduct, onOpenExisting, existingQuote, showBindingBanner = false }: { onSelectProduct: () => void; onOpenExisting: () => void; existingQuote: string; showBindingBanner?: boolean }) { return <>{showBindingBanner && <BindingBanner />}<Header /><SearchBar /><main className="mx-auto grid max-w-[1440px] grid-cols-1 gap-4 px-4 py-4 lg:grid-cols-[220px_minmax(0,1fr)_240px] xl:grid-cols-[235px_minmax(0,1fr)_250px]"><LeftColumn onSelect={onSelectProduct} onOpenExisting={onOpenExisting} existingQuote={existingQuote} /><div className="space-y-3"><AlertsPanel /><AgencyNews /></div><aside className="space-y-3"><PartnershipCard /><BottomStats /></aside></main><footer className="mx-auto max-w-[1440px] px-4 pb-4 text-[10px] text-[#667582]"><FileText size={12} className="mr-1 inline" /> Agent portal dashboard</footer></>; }
